// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetAllCategories~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Category.ICategory}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetAllQuestions~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Posts.IQuestion}")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetAllUsers~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.User.IUser}")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetAnswersOfUser(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Posts.Answer}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetBadgesOfUser(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Badge.IBadge}")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetCategoriesModeratedByUser(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Category.ICategory}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetCommentsOfUser(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.IPost}")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetNotificationsOfUser(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Notification.INotification}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetQuestionsOfUser(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Posts.IQuestion}")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetReactionsOfPostByPostID(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Reactions.IReaction}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetRepliesOfPost(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.IPost}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:UBB_SE_2024_Team_42.TSQLRepository.TSQLRepository.GetTagsOfQuestion(System.Int64)~System.Collections.Generic.List{UBB_SE_2024_Team_42.Domain.Tag.ITag}")]
